config/routes.rb
Remindavax::Application.routes.draw do

	root :to => "sessions#new"
	match "log_out" => "sessions#destroy", :as => "log_out"
	match "log_in" => "sessions#new", :as => "log_in"
	match "sign_up" => "patients#new", :as => "sign_up"
	match "settings" => "settings#edit", :as => "settings"
	
	resources :patients
	resources :settings
	resources :sessions
	resources :drugs

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  attr_accessible :name, :phone, :email
  has_many :patients
end

app/models/dosage.rb
class Dosage < ActiveRecord::Base
  attr_accessible :amount, :unit
  belongs_to :drug

  validates :amount, :unit, :presence => true
  validates :amount, :numericality => true
  

end

app/models/drug.rb
class Drug < ActiveRecord::Base  
  belongs_to :patient
  has_one :dosage
  has_one :frequency
  accepts_nested_attributes_for :dosage, :frequency
	attr_accessible :name, :treatmentname, :days_worth_of_medication,
		:refill_date, :dosage_attributes, :frequency_attributes
  after_initialize :default_values 
	
	validates :name, :treatmentname, :refill_date, :presence => true
	validates :days_worth_of_medication, :numericality => {:only_integer => true}
	validate :refill_date_cannot_be_in_the_past

  DRUGS = ['advair 100/50', 'advair 250/50', 'advair 500/50', 'advair diskus',
            'advair hfa 45/21', 'flovent 110', 'flovent 22']
	
  private
  def refill_date_cannot_be_in_the_past
		if !refill_date.blank? and refill_date < Date.today
			errors.add(:refill_date, "can't be in the past")
		end
	end

  def default_values
    if self.new_record?
      self.days_worth_of_medication = 1
    end
  end
 
end

app/models/frequency.rb
class Frequency < ActiveRecord::Base
  attr_accessible :days_per_week, :times_per_day, :weeks_per_month
  belongs_to :drug
  after_initialize :default_values

  validates :days_per_week, :times_per_day, :weeks_per_month, 
    :numericality => true

  private
  def default_values
    if self.new_record?
      self.days_per_week = 1
      self.times_per_day = 1
      self.weeks_per_month = 1
    end
  end
  
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :drugs
  has_one :setting
  has_many :preferred_times, :through => :setting
  belongs_to :doctor 
  belongs_to :sponsor
  
  attr_accessible :email, :password, :password_confirmation, :firstname, :lastname, :phone
  attr_accessor :password
  before_save :encrypt_password
  
  validates :firstname, :lastname, :phone, :presence => true
  validates :email, :presence => true, :uniqueness => true
  validates :password, :presence => true, :confirmation => true, 
  			:on => :create
  			
  def self.authenticate(email, password)
  	patient = find_by_email(email)
  	if patient && patient.password_hash == BCrypt::Engine.hash_secret(password, patient.password_salt)
  		patient
  	else
  		nil 
  	end
  end
  
  def encrypt_password
  	if password.present?
  		self.password_salt = BCrypt::Engine.generate_salt
  		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  	end
  end
  
end

app/models/preferred_time.rb
class PreferredTime < ActiveRecord::Base
  attr_accessible :time_to_receive_reminder
  belongs_to :setting
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  attr_accessible :is_active, :reminder_preferred_times, :reminder_summary, 
  :send_by_email, :send_by_text
  
  belongs_to :patient
  has_many :preferred_times
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  has_many :patients
  attr_accessible :firstname, :lastname, :email, :phone, :password, :passwordconfirmation

  validates :firstname, :lastname, :phone, :presence => true
  validates :email, :presence => true, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_patient
  
  private 
  def current_patient
  	@current_patient ||= Patient.find(session[:patient_id]) if session[:patient_id]
  end

end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  # GET /drugs
  # GET /drugs.json
  def index
    @drugs = current_patient.drugs.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @drugs }
    end
  end

  # GET /drugs/1
  # GET /drugs/1.json
  def show
    @drug = Drug.includes(:dosage, :frequency).find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @drug }
    end
  end

  # GET /drugs/new
  # GET /drugs/new.json
  def new
    @drug = Drug.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /drugs/1/edit
  def edit
    @drug = Drug.find(params[:id])
  end

  # POST /drugs
  # POST /drugs.json
  def create
    @drug = current_patient.drugs.new(params[:drug])

    respond_to do |format|
      if @drug.save
        format.html { redirect_to @drug, notice: 'Drug was successfully created.' }
        format.json { render json: @drug, status: :created, location: @drug }
      else
        format.html { render action: "new" }
        format.json { render json: @drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /drugs/1
  # PUT /drugs/1.json
  def update
    @drug = Drug.find(params[:id])

    respond_to do |format|
      if @drug.update_attributes(params[:drug])
        format.html { redirect_to @drug, notice: 'Drug was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drugs/1
  # DELETE /drugs/1.json
  def destroy
    @drug = Drug.find(params[:id])
    @drug.destroy

    respond_to do |format|
      format.html { redirect_to drugs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
def new 
	@patient = Patient.new
end

def create 
	@patient = Patient.new(params[:patient])
	if @patient.save 
		redirect_to root_url, :notice => "You have been registered"
	else
		render "new"
	end
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new 
end

def create 
	patient = Patient.authenticate(params[:email], params[:password])
	if patient
		session[:patient_id] = patient.id 
		redirect_to drugs_url, :notice => "Logged in"
	else
		flash.now.alert = "Invalid email or password"
		render "new"
	end
end

def destroy 
	session[:patient_id] = nil 
	redirect_to root_url, :notice => "Logged out!"
end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  def edit 
    @setting = Setting.find_or_create_by_patient_id(current_patient.id,
                                                    :send_by_text => false,
                                                    :send_by_email => false,
                                                    :reminder_summary => false,
                                                    :reminder_preferred_times => false,
                                                    :is_active => false)
  end

  def update 
    @setting = Setting.find_by_patient_id(current_patient.id)
    if @setting.update_attributes(params[:setting])

      redirect_to settings_path
      #using redirect_to makes an extra call and
      #produces extra overhead. We need to change this later.
      #using this would be better:
      #render "edit", :flash => "Settings saved!"
     
    else
      render "edit", :alert => "Settings failed to save!"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drugs_helper.rb
module DrugsHelper
  def setup_drug(drug)
    drug.dosage ||= Dosage.new
    drug.frequency ||= Frequency.new
    drug
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/drugs/_form.html.erb
<%= form_for(setup_drug(@drug)) do |f| %>
  <% if @drug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drug.errors.count, "error") %> prohibited this drug from being saved:</h2>

      <ul>
      <% @drug.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<p>
		<%= f.label :name %><br />
		<%= f.collection_select :name, Drug::DRUGS, :to_s, :to_s, :prompt => 'Select' %>
	</p>
	<p>
		<%= f.label :treatmentname %><br />
		<%= f.text_field :treatmentname %>
	</p>
	<p>
		<%= f.label(:days_worth_of_medication, "Days worth of medication") %><br />
		<%= f.number_field :days_worth_of_medication, :min => 1%>
	</p>
	<p>
		<%= f.label(:refill_date, "Refill date")%><br />
		<%= f.date_select :refill_date %>
	</p>

  <%= f.fields_for :dosage do |d|%>
    <p>
      <%= d.label :amount %><br />
      <%= d.text_field :amount %>
    </p>
    <p>
      <%= d.label :unit %><br />
      <%= d.text_field :unit %>
    </p>
  <% end %>

  <%= f.fields_for :frequency do |fr| %>
    <p>
      <%= fr.label(:times_per_day, "Times per Day")%><br />
      <%= fr.number_field :times_per_day, :min => 1%>
    </p>
    <p>
      <%= fr.label(:days_per_week, "Days per Week")%><br />
      <%= fr.number_field :days_per_week, :min => 1%>
    </p>
    <p>
      <%= fr.label(:weeks_per_month, "Weeks per Month")%><br />
      <%= fr.number_field :weeks_per_month, :min => 1%>
    </p>
  <% end %>
  <div class="actions">
    <%= f.submit "Add Medication" %>
  </div>
<% end %>

app/views/drugs/edit.html.erb
<h1>Editing drug</h1>

<%= render 'form' %>

<%= link_to 'Show', @drug %> |
<%= link_to 'Back', drugs_path %>

app/views/drugs/index.html.erb
<h1>Listing drugs</h1>

<table>
  <tr>
    <th>Drug name</th>
    <th>Treatment name</th>
    <th>Days worth of Medication</th>
    <th>Refill Date</th>
  </tr>

<% @drugs.each do |drug| %>
  <tr>
  	<td><%= drug.name %></td>
  	<td><%= drug.treatmentname %></td>
  	<td><%= drug.days_worth_of_medication %></td>
  	<td><%= drug.refill_date %></td>
    <td><%= link_to 'Show', drug %></td>
    <td><%= link_to 'Edit', edit_drug_path(drug) %></td>
    <td><%= link_to 'Destroy', drug, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Drug', new_drug_path %>

app/views/drugs/new.html.erb
<h1>Add Medication</h1>

<%= render 'form' %>


<%= link_to 'Back', drugs_path %>

app/views/drugs/show.html.erb
<p id="notice"><%= notice %></p>
 
<p>
  <b>Name:</b>
  <%= @drug.name %>
</p>
 
<p>
  <b>Treatment Name:</b>
  <%= @drug.treatmentname %>
</p>
 
<p>
  <b>Days worth of Medication:</b>
  <%= @drug.days_worth_of_medication %>
</p>

<p>
	<b>Refill Date:</b>
	<%= @drug.refill_date %>
</p>
<p>
	<b>Amount</b>
	<%= @drug.dosage.amount %>
</p>
<p>
  <b>Unit</b>
  <%= @drug.dosage.unit %>
</p>
<p>
  <b>Times per Day:</b>
  <%= @drug.frequency.times_per_day %>
</p>
<p>
  <b>Days per Week:</b>
  <%= @drug.frequency.days_per_week %>
</p>
<p>
  <b>Weeks per Month:</b>
  <%= @drug.frequency.weeks_per_month %>
</p>
<p>
	<b>Last Updated:</b>
	<%= @drug.updated_at %>
</p>
<%= link_to 'Edit', edit_drug_path(@drug) %> |
<%= link_to 'Back', drugs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Remindavax</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">
	<% if current_patient %>
		Logged in as <%= current_patient.email %>.
		<%= link_to "Log out", log_out_path %><br />
		<%= link_to "Regimen", drugs_path %>
		<%= link_to "Settings", settings_path %>
	<% else %>
		<%= link_to "Log in", log_in_path %> or
		<%= link_to "Sign up", sign_up_path %>
	<% end %>
</div>

<% flash.each do |name, msg| %>
	<%= content_tag :div, msg, :id => "flash_#{name}"%>
<% end %>

<%= yield %>

</body>
</html>

app/views/patients/new.html.erb
<h1> Register </h1>

<%= form_for @patient do |f| %>
	<% if @patient.errors.any? %>
	<div class="error_messages">
		<h2>Form is invalid</h2>
		<ul>
			<% for message in @patient.errors.full_messages %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	
	<p>
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.label :password_confirmation %><br />
		<%= f.password_field :password_confirmation %> 
	</p>
	<p>
		<%= f.label :firstname %><br />
		<%= f.text_field :firstname %>
	</p>
	<p>
		<%= f.label :lastname %><br />
		<%= f.text_field :lastname %>
	</p>
	<p>
		<%= f.label :phone %><br />
		<%= f.text_field :phone %>
	</p>
		
	<%= submit_tag "register", :class => "button"%>
	
<% end %>

app/views/settings/edit.html.erb
<h1> Settings </h1>

<%= form_for @setting do |s| %>
	<% if @setting.errors.any? %>
	<div class="error_messages">
		<h2>Form is invalid</h2>
		<ul>
			<% for message in @setting.errors.full_messages %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	
	<p>
		<%= s.label :send_by_text %><br />
		<%= s.check_box :send_by_text %>
	</p>
	<p>
		<%= s.label :send_by_email %><br />
		<%= s.check_box :send_by_email %>
	</p>
	<p>
		<%= s.label :reminder_summary %><br />
		<%= s.check_box :reminder_summary %>
	</p>
	<p>
		<%= s.label :reminder_preferred_times %><br />
		<%= s.check_box :reminder_preferred_times %>
	</p>
	<p>
		<%= s.label :is_active %><br />
		<%= s.check_box :is_active %>
	</p>
		
	<%= submit_tag "Save Changes", :class => "button"%>
	
<% end %>